### ISSUE TITLE
Code Integration

### ISSUE THREAD

**Issue by AnandSingh-0619** [AnandSingh-0619/home-robot#1]
https://github.com/AnandSingh-0619/home-robot/blob/f3f8207f8a0689f4bdad21c6715f9bed1400eab3/projects/habitat_uncertainity/sensors.py#L75C1-L83C35

The model and wts are called in the YOLO_pred file where the predict function returns the new observations. A new YOLO_ObjectSegmentationSensor which should be replaced with original for object segmentation. I need steps to integrate this to the main code.
@yusufali98

**Comment by yusufali98** [comment]
You need to follow the OVON codebase structure. This is how you should achieve this:

1. Look closely as to how the custom sensors are created within the ovon directory. Sensors are defined in the tasks/ folder in [sensors.py](https://github.com/naokiyokoyama/ovon/blob/main/ovon/task/sensors.py)
2. Consider the [ClipObjectGoalSensor](https://github.com/naokiyokoyama/ovon/blob/main/ovon/task/sensors.py#L22). once the sensor is defined you need to create a hydra config for the same as is done [here](https://github.com/naokiyokoyama/ovon/blob/main/ovon/config.py#L28)
3. Then you need to register the config data class with the hydra config store as is done [here](https://github.com/naokiyokoyama/ovon/blob/main/ovon/config.py#L226) 
4. You also need to create the [search path plugin](https://github.com/naokiyokoyama/ovon/blob/main/ovon/config.py#L324) and need to [register the plugin](https://github.com/naokiyokoyama/ovon/blob/main/ovon/run.py#L15-L19) in the run.py file that you will use to run any experiments.
5. The [DDPPO training in home-robot](https://github.com/AnandSingh-0619/home-robot/tree/f3f8207f8a0689f4bdad21c6715f9bed1400eab3/projects/habitat_ovmm#training-dd-ppo-skills) uses the built-in habitat_baselines [run.py](https://github.com/facebookresearch/habitat-lab/blob/b727ca9f7123101aaedb737ca9ccc1b153525dd9/habitat-baselines/habitat_baselines/run.py) file. So as done in the OVON codebase, you need to create a new run.py within habitat_uncertainty project folder in which you will just register the hydra plugin (step 4) and basically import the execute_exp function from the habitat_baselines run.py ([this](https://github.com/naokiyokoyama/ovon/blob/main/ovon/run.py#L12) and [this](https://github.com/naokiyokoyama/ovon/blob/main/ovon/run.py#L136))

Basically, you need to exactly replicate the OVON code structure and make sure you never make any changes in the habitat-lab/habitat-baselines codebase.

Regarding your question of the custom OVON trainers, they will only be used if specified in the config as is done [here](https://github.com/naokiyokoyama/ovon/blob/main/config/experiments/transformer_rl.yaml#L36C18-L36C33) to use [this particular](https://github.com/naokiyokoyama/ovon/blob/main/ovon/trainers/ver_transformer_trainer.py#L75) custom trainer. We dont need to do all this because you will just use the standard habitat_baselines trainer that is specified in the [rl_skill.yaml ](https://github.com/facebookresearch/habitat-lab/blob/b727ca9f7123101aaedb737ca9ccc1b153525dd9/habitat-baselines/habitat_baselines/config/ovmm/rl_skill.yaml#L14) ([this trainer](https://github.com/facebookresearch/habitat-lab/blob/b727ca9f7123101aaedb737ca9ccc1b153525dd9/habitat-baselines/habitat_baselines/rl/ppo/ppo_trainer.py#L75))

**Comment by yusufali98** [comment]
Also, please make sure you link the correct branch in the GitHub issue. Linking incorrect branches can cause issues. 
Right now you have linked [this branch](https://github.com/AnandSingh-0619/home-robot/blob/f3f8207f8a0689f4bdad21c6715f9bed1400eab3/projects/habitat_uncertainity/sensors.py#L75C1-L83C35) 
But I am guessing you wanted to link [your dev branch](https://github.com/AnandSingh-0619/home-robot/blob/anand_dev/projects/habitat_uncertainity/sensors.py)
